// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VehicleWebApp.Service.Contexts;

namespace VehicleWebApp.MVC.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20190503081406_bla")]
    partial class bla
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("VehicleWebApp.Service.Models.VehicleMake", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Abbreviation");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.HasKey("Id");

                    b.ToTable("VehicleMakes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            Name = "Peugeot"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000002"),
                            Abbreviation = "Bembara",
                            Name = "BMW"
                        });
                });

            modelBuilder.Entity("VehicleWebApp.Service.Models.VehicleModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Abbreviation");

                    b.Property<Guid>("MakeId");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.HasKey("Id");

                    b.HasIndex("MakeId");

                    b.ToTable("VehicleModels");

                    b.HasData(
                        new
                        {
                            Id = new Guid("4a4b6dd7-21cb-4a53-aa65-fdac08036e0b"),
                            MakeId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Name = "206"
                        },
                        new
                        {
                            Id = new Guid("c85ab8ef-facc-4da2-bac2-67ce92719f09"),
                            Abbreviation = "Dvjestosedmica",
                            MakeId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Name = "207"
                        },
                        new
                        {
                            Id = new Guid("aac39be9-d4c8-46ee-aa1e-b68ac79386f6"),
                            MakeId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Name = "M4"
                        });
                });

            modelBuilder.Entity("VehicleWebApp.Service.Models.VehicleModel", b =>
                {
                    b.HasOne("VehicleWebApp.Service.Models.VehicleMake", "Make")
                        .WithMany("Models")
                        .HasForeignKey("MakeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
