// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VehicleWebApp.Service.Contexts;

namespace VehicleWebApp.MVC.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20190415121442_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("VehicleWebApp.Service.Models.VehicleMake", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Abbreviation");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.HasKey("Id");

                    b.ToTable("VehicleMakes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            Name = "Peugeot"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000002"),
                            Abbreviation = "Bembara",
                            Name = "BMW"
                        });
                });

            modelBuilder.Entity("VehicleWebApp.Service.Models.VehicleModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Abbreviation");

                    b.Property<Guid>("MakeId");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.HasKey("Id");

                    b.HasIndex("MakeId");

                    b.ToTable("VehicleModels");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f2bfe8b6-2c38-42c2-bfb1-f70ec473b202"),
                            MakeId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Name = "206"
                        },
                        new
                        {
                            Id = new Guid("f2403a4a-7e4f-464d-993d-3934d71ad17f"),
                            Abbreviation = "Dvjestosedmica",
                            MakeId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Name = "207"
                        },
                        new
                        {
                            Id = new Guid("f75c98f6-126e-44f2-876c-2deba2d4f2e5"),
                            MakeId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Name = "M4"
                        });
                });

            modelBuilder.Entity("VehicleWebApp.Service.Models.VehicleModel", b =>
                {
                    b.HasOne("VehicleWebApp.Service.Models.VehicleMake", "Make")
                        .WithMany("Models")
                        .HasForeignKey("MakeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
