// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VehicleWebApp.Service.Contexts;

namespace VehicleWebApp.MVC.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20190501114156_Migration005")]
    partial class Migration005
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("VehicleWebApp.Service.Models.VehicleMake", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Abbreviation");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.HasKey("Id");

                    b.ToTable("VehicleMakes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            Name = "Peugeot"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000002"),
                            Abbreviation = "Bembara",
                            Name = "BMW"
                        });
                });

            modelBuilder.Entity("VehicleWebApp.Service.Models.VehicleModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Abbreviation");

                    b.Property<Guid>("MakeId");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.HasKey("Id");

                    b.HasIndex("MakeId");

                    b.ToTable("VehicleModels");

                    b.HasData(
                        new
                        {
                            Id = new Guid("833ba509-7830-4385-b39b-4b8007cd319b"),
                            MakeId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Name = "206"
                        },
                        new
                        {
                            Id = new Guid("3bb3a34f-02c0-4c73-abbe-374f1b2730db"),
                            Abbreviation = "Dvjestosedmica",
                            MakeId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Name = "207"
                        },
                        new
                        {
                            Id = new Guid("994b4530-1a8a-4460-a50b-dcc0682526a5"),
                            MakeId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Name = "M4"
                        });
                });

            modelBuilder.Entity("VehicleWebApp.Service.Models.VehicleModel", b =>
                {
                    b.HasOne("VehicleWebApp.Service.Models.VehicleMake", "Make")
                        .WithMany("Models")
                        .HasForeignKey("MakeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
