// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VehicleWebApp.Service.Contexts;

namespace VehicleWebApp.MVC.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20190415203228_Migration002")]
    partial class Migration002
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("VehicleWebApp.Service.Models.VehicleMake", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Abbreviation");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.HasKey("Id");

                    b.ToTable("VehicleMakes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            Name = "Peugeot"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000002"),
                            Abbreviation = "Bembara",
                            Name = "BMW"
                        });
                });

            modelBuilder.Entity("VehicleWebApp.Service.Models.VehicleModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Abbreviation");

                    b.Property<Guid>("MakeId");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.HasKey("Id");

                    b.HasIndex("MakeId");

                    b.ToTable("VehicleModels");

                    b.HasData(
                        new
                        {
                            Id = new Guid("27a23679-9a05-40b0-ad23-66d89d841897"),
                            MakeId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Name = "206"
                        },
                        new
                        {
                            Id = new Guid("bad150af-396c-4860-b46f-ee67cfa017fe"),
                            Abbreviation = "Dvjestosedmica",
                            MakeId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Name = "207"
                        },
                        new
                        {
                            Id = new Guid("b77a87ff-a399-45b1-ae64-b9830d1556d9"),
                            MakeId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Name = "M4"
                        });
                });

            modelBuilder.Entity("VehicleWebApp.Service.Models.VehicleModel", b =>
                {
                    b.HasOne("VehicleWebApp.Service.Models.VehicleMake", "Make")
                        .WithMany("Models")
                        .HasForeignKey("MakeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
